### ISSUE TITLE
Suggestion for get_midi_host

### ISSUE THREAD

**Issue by moseltronics** [rppicomidi/usb_midi_host#11]
Hi rppicomidi,

i managed to build an extended version of midi2usb host (with 3 USB connections) and had to make some tweaks.

One was to change the code for get_midi_host to the following:
`
static midih_interface_t *get_midi_host(uint8_t dev_addr)
{
  TU_VERIFY(dev_addr >0 && dev_addr <= CFG_TUH_DEVICE_MAX);
  //return (_midi_host + dev_addr - 1);
  return &(_midi_host[dev_addr - 1]);
}
`
This worked for me. Maybe this solves some reported problems with multiple devices.

**Comment by moseltronics** [comment]
Sorry, the code didn't look as i wanted  ...

static midih_interface_t *get_midi_host(uint8_t dev_addr)

 { TU_VERIFY(dev_addr >0 && dev_addr <= CFG_TUH_DEVICE_MAX);

 //return (_midi_host + dev_addr - 1);  //seams to work only if dev_addr == 1

return &(_midi_host[dev_addr - 1]); 
}

**Comment by rppicomidi** [comment]
Thank you for this suggestion. I will investigate it.

**Comment by rppicomidi** [comment]
@moseltronics I have tried the suggested code change because I was concerned there was something strange with the pico-sdk
C compiler. As I expected, whether I use the suggested code change or not, `get_midi_host()` returns the same value for the same value of dev_addr. This is the expected result.

May I suggest that now that your system is functioning, will you please revert the suggested change and see if it still works?
If you see a different result depending on whether you use your suggested change or the original code, I will need more
information about your build environment to help you figure out what is going on.

Please tell me whether you are using Arduino IDE or the pico-sdk. If the pico-sdk, please tell me the pico-sdk version and what version of gcc you are using to build the code. If the Arduino IDE, please tell me the version of the Arduino IDE and the version
of the Earle Philhower Raspberry Pi Pico board package you are using, and what version of all libraries you are using. Please
also tell me whether you are using a PC, Mac, or Linux computer to build your code. Finally, please tell me what target hardware
you use.

**Comment by moseltronics** [comment]
Hi rppicomidi,

your totally right.

I tried everything out and found that both versions work the same way. So sorry for bothering you ...

Changing the callback functions must have made the difference in my code.

Have a nice day ...

**Comment by rppicomidi** [comment]
@moseltronics OK. It was no bother. If you discover there is a problem after all, please re-open this issue. Thank you for taking the time to file the issue in the first place.
